twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel
        timeout: 0.20
        priority: 10
      tracker:
        topic: cmd_vel_tracker
        timeout: 0.50
        priority: 20  
      teleop_keyboard:
        topic: teleop_cmd_vel
        timeout: 0.5
        priority: 100